In [1]:
import numpy as np
import torch
import torch.nn as nn

##### nn.Linear layer

In [10]:
torch.manual_seed(2023)
input = torch.randn(2, 4)
print(input.size())
print(input)

torch.Size([2, 4])
tensor([[-1.2075,  0.5493, -0.3856,  0.6910],
        [-0.7424,  0.1570,  0.0721,  1.1055]])


In [11]:
m = nn.Linear(in_features=4, out_features=3, bias=False)
print(m)

Linear(in_features=4, out_features=3, bias=False)


In [12]:
m.weight

Parameter containing:
tensor([[-0.2568,  0.4644,  0.0034, -0.4680],
        [ 0.3316, -0.1193, -0.1461, -0.2886],
        [ 0.4839,  0.1632,  0.2001, -0.4845]], requires_grad=True)

In [13]:
output = m(input)
print(output.shape)
print(output)

torch.Size([2, 3])
tensor([[ 0.2406, -0.6090, -0.9066],
        [-0.2534, -0.5945, -0.8548]], grad_fn=<MmBackward0>)


In [17]:
output_matmul = np.matmul(input, m.weight.T.detach().numpy())
print(output_matmul)

tensor([[ 0.2406, -0.6090, -0.9066],
        [-0.2534, -0.5945, -0.8548]])


In [19]:
output.detach() == output_matmul

tensor([[True, True, True],
        [True, True, True]])