In [1]:
import numpy as np
import torch
import torch.nn as nn

##### nn.Linear layer

In [10]:
torch.manual_seed(2023)
input = torch.randn(2, 4)
print(input.size())
print(input)

torch.Size([2, 4])
tensor([[-1.2075,  0.5493, -0.3856,  0.6910],
        [-0.7424,  0.1570,  0.0721,  1.1055]])


In [11]:
m = nn.Linear(in_features=4, out_features=3, bias=False)
print(m)

Linear(in_features=4, out_features=3, bias=False)


In [12]:
m.weight

Parameter containing:
tensor([[-0.2568,  0.4644,  0.0034, -0.4680],
        [ 0.3316, -0.1193, -0.1461, -0.2886],
        [ 0.4839,  0.1632,  0.2001, -0.4845]], requires_grad=True)

In [13]:
output = m(input)
print(output.shape)
print(output)

torch.Size([2, 3])
tensor([[ 0.2406, -0.6090, -0.9066],
        [-0.2534, -0.5945, -0.8548]], grad_fn=<MmBackward0>)


In [17]:
output_matmul = np.matmul(input, m.weight.T.detach().numpy())
print(output_matmul)

tensor([[ 0.2406, -0.6090, -0.9066],
        [-0.2534, -0.5945, -0.8548]])


In [19]:
output.detach() == output_matmul

tensor([[True, True, True],
        [True, True, True]])

##### Conv2d layer

In [20]:
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
from torchvision import datasets

In [21]:
mnist_transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean=(0.5,), std=(1.0,))])

In [27]:
trainset = datasets.MNIST(root='data/', train=True, download=True, transform=mnist_transform)
testset = datasets.MNIST(root='data/', train=False, download=True, transform=mnist_transform)

In [28]:
# DataLoader는 dataset전체를 보관했다가 batch_size크기만클 data를 가져온다.
train_loader = DataLoader(trainset, batch_size=8, shuffle=True, num_workers=2)
test_loader = DataLoader(testset, batch_size=8, shuffle=False, num_workers=2)

In [29]:
# data를 loader를 이용해서 iteration으로 가져온다.
dataiter = iter(train_loader)
images, labels = next(dataiter)
print(images.size(), labels.size())

torch.Size([8, 1, 28, 28]) torch.Size([8])


In [33]:
torch.cuda.is_available()

True

In [35]:
layer = nn.Conv2d(in_channels=1, out_channels=20, kernel_size=5, stride=1).to(torch.device('cpu'))

In [36]:
weight = layer.weight.detach().numpy()
print(weight.shape)

(20, 1, 5, 5)


In [37]:
print(f"images shape : {images.shape}")
print(f"images[0] size : {images[0].size()}")

images shape : torch.Size([8, 1, 28, 28])
images[0] size : torch.Size([1, 28, 28])
