In [1]:
import torch
torch.__version__

'1.13.0'

In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [5]:
x = torch.empty(4,2)
print(x)

tensor([[6.3058e-44, 6.7262e-44],
        [7.1466e-44, 6.3058e-44],
        [7.0065e-44, 7.1466e-44],
        [1.1771e-43, 6.7262e-44]])


In [6]:
x = torch.rand(4,2)
print(x)

tensor([[0.0038, 0.2834],
        [0.9550, 0.3880],
        [0.4715, 0.6432],
        [0.4175, 0.9395]])


In [8]:
x = torch.randn(4,2)
print(x)

tensor([[ 0.4675,  1.2517],
        [-0.1044, -1.5934],
        [ 0.8494,  0.0801],
        [-0.5682, -0.3965]])


In [10]:
x = torch.zeros(4,2, dtype=torch.long)
print(x)

y = torch.zeros(4,2, dtype=torch.double)
print(y)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)


In [14]:
x = torch.tensor([3, 2.3], dtype=torch.half)
print(x)

tensor([3.0000, 2.3008], dtype=torch.float16)


In [19]:
x = x.new_ones(2,5, dtype=torch.int)
print(x)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)


In [20]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.1877,  2.2573,  1.6946,  1.0309, -0.3665],
        [ 0.0156,  0.6785, -0.1894,  1.9779,  1.4175]])


In [21]:
x = torch.ones(2,4, dtype=torch.float)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
