In [1]:
import sys
print(sys.executable)
print()
for p in sys.path:
    print(p)

C:\Users\rubin\anaconda3\envs\tf_gpu\python.exe

E:\PYTORCH_2023
C:\Users\rubin\anaconda3\envs\tf_gpu\python39.zip
C:\Users\rubin\anaconda3\envs\tf_gpu\DLLs
C:\Users\rubin\anaconda3\envs\tf_gpu\lib
C:\Users\rubin\anaconda3\envs\tf_gpu

C:\Users\rubin\anaconda3\envs\tf_gpu\lib\site-packages
C:\Users\rubin\anaconda3\envs\tf_gpu\lib\site-packages\win32
C:\Users\rubin\anaconda3\envs\tf_gpu\lib\site-packages\win32\lib
C:\Users\rubin\anaconda3\envs\tf_gpu\lib\site-packages\Pythonwin


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import tensorflow as tf
import torch

In [3]:
print(torch.cuda.is_available())

True


In [4]:
torch.__version__

'1.13.0'

## 파이토치(Pytorch)

- 페이스북이 초기 루아(Lua)언어로 개발된 토치(Torch)를 파이썬 버전으로 개발하여 2017년에 공개
- 초기에 Torch는 Numpy 라이브러리처럼 과학 연산을 위한 라이브러리로 공개
- 이후 병렬처리를 지원하는 GPU를 이용한 tensor조작 및 동적 신경망 구축이 가능하도록 Deep Learning Framework로 발전시킴
- 파이썬답게 만들어졌고 유연하면서도 가속화된 계산 속도를 제공

## 파이토치의 구성요소

- torch : 메인 네임스페이스, 텐서등의 다양한 수학 함수가 포함
- torch.autograd : 자동 미분 기능을 제공하는 라이브러리
- torch.nn : 신경망 구축을 위한 데이터 구조나 레이어 등의 라이브러리
- torch.multiprocessing : 병렬처리 기능을 제공하는 라이브러리
- torch.optim : SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화 알고리즘 제공
- torch.utils : 데이터 조작 등 유틸리티 기능 제공
- torch.onnx : ONNX(Open Neural Network Exchange), 서로 다른 프레임워크 간의 모델을 공유할 때 사용

## 텐서(Tensors)

- 데이터 표현을 위한 기본 구조로 텐서(tensor)를 이용
- 텐서는 데이터를 담기 위한 container로서 일반적으로 수치형 데이터를 저장
- Numpy의 ndarray와 유사
- GPU를 사용한 연산 가속 가능

    - 0D Tensor(Scalar) : Rank=0, Shape=()
    - 1D Tensor(Vector) : Rank=1, Shape=(3,)
    - 2D Tensor(Matrix) : Rank=2, Shape=(3,3)
    - 3D Tensor         : Rank=3, Shape=(3,3,3)
    - 4D Tensor         : Rank=4, Shape=(3,3,3,3)
    - 5D Tensor         : Rank=5, Shape=(3,3,3,3,3)
    - 6D Tensor         : Rank=6, Shape=(3,3,3,3,3,3)

## 텐서 초기화와 데이터 타입

In [5]:
# 초기화 되지 않은 텐서
x = torch.empty(4,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [6]:
# 무작위로 초기화된 텐서
x = torch.rand(4,2)
print(x)

tensor([[0.6384, 0.2514],
        [0.0530, 0.2637],
        [0.4188, 0.9970],
        [0.5437, 0.8281]])


In [8]:
# 데이터타입이 long이고 0으로 채워진 텐서
x = torch.zeros(4,2, dtype=torch.long)
print(x)  # 타입이 long이므로 소수점이 없이 정수형태로 초기화되었다

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [20]:
# 사용자가 입력한 값으로 텐서 초기화
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [21]:
# 2*4크기, double타입, 1로 채워진 텐서
x = x.new_ones(2,4, dtype=torch.double)
print(x)
print()
y= torch.ones(2,4, dtype=torch.double)
print(x)
print()
print(x == y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

tensor([[True, True, True, True],
        [True, True, True, True]])


In [22]:
# x와 같은 크기, float타입, 무작위로 채워진 텐서
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.4344, -0.7893,  0.2959, -2.0637],
        [ 0.9515, -0.0663, -0.8114,  0.6558]])


In [23]:
# 텐서의 크기 계산
print(x.size())

torch.Size([2, 4])
