In [1]:
import sys
print(sys.executable)
print()
for p in sys.path:
    print(p)

C:\Users\rubin\anaconda3\envs\tf_gpu\python.exe

E:\PYTORCH_2023
C:\Users\rubin\anaconda3\envs\tf_gpu\python39.zip
C:\Users\rubin\anaconda3\envs\tf_gpu\DLLs
C:\Users\rubin\anaconda3\envs\tf_gpu\lib
C:\Users\rubin\anaconda3\envs\tf_gpu

C:\Users\rubin\anaconda3\envs\tf_gpu\lib\site-packages
C:\Users\rubin\anaconda3\envs\tf_gpu\lib\site-packages\win32
C:\Users\rubin\anaconda3\envs\tf_gpu\lib\site-packages\win32\lib
C:\Users\rubin\anaconda3\envs\tf_gpu\lib\site-packages\Pythonwin


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import tensorflow as tf
import torch

In [3]:
print(torch.cuda.is_available())

True


In [4]:
torch.__version__

'1.13.0'

## 파이토치(Pytorch)

- 페이스북이 초기 루아(Lua)언어로 개발된 토치(Torch)를 파이썬 버전으로 개발하여 2017년에 공개
- 초기에 Torch는 Numpy 라이브러리처럼 과학 연산을 위한 라이브러리로 공개
- 이후 병렬처리를 지원하는 GPU를 이용한 tensor조작 및 동적 신경망 구축이 가능하도록 Deep Learning Framework로 발전시킴
- 파이썬답게 만들어졌고 유연하면서도 가속화된 계산 속도를 제공

## 파이토치의 구성요소

- torch : 메인 네임스페이스, 텐서등의 다양한 수학 함수가 포함
- torch.autograd : 자동 미분 기능을 제공하는 라이브러리
- torch.nn : 신경망 구축을 위한 데이터 구조나 레이어 등의 라이브러리
- torch.multiprocessing : 병렬처리 기능을 제공하는 라이브러리
- torch.optim : SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화 알고리즘 제공
- torch.utils : 데이터 조작 등 유틸리티 기능 제공
- torch.onnx : ONNX(Open Neural Network Exchange), 서로 다른 프레임워크 간의 모델을 공유할 때 사용

## 텐서(Tensors)

- 데이터 표현을 위한 기본 구조로 텐서(tensor)를 이용
- 텐서는 데이터를 담기 위한 container로서 일반적으로 수치형 데이터를 저장
- Numpy의 ndarray와 유사
- GPU를 사용한 연산 가속 가능

    - 0D Tensor(Scalar) : Rank=0, Shape=()
    - 1D Tensor(Vector) : Rank=1, Shape=(3,)
    - 2D Tensor(Matrix) : Rank=2, Shape=(3,3)
    - 3D Tensor         : Rank=3, Shape=(3,3,3)
    - 4D Tensor         : Rank=4, Shape=(3,3,3,3)
    - 5D Tensor         : Rank=5, Shape=(3,3,3,3,3)
    - 6D Tensor         : Rank=6, Shape=(3,3,3,3,3,3)

## 텐서 초기화와 데이터 타입

In [5]:
# 초기화 되지 않은 텐서
x = torch.empty(4,2)
print(x)

tensor([[7.8675e+34, 4.6894e+27],
        [1.6217e-19, 1.4333e-19],
        [2.7530e+12, 7.5338e+28],
        [8.1173e-10, 3.5873e-43]])


In [6]:
# 무작위로 초기화된 텐서
x = torch.rand(4,2)
print(x)

tensor([[0.1834, 0.3772],
        [0.2033, 0.1296],
        [0.5581, 0.2812],
        [0.5279, 0.8109]])


In [7]:
# 데이터타입이 long이고 0으로 채워진 텐서
x = torch.zeros(4,2, dtype=torch.long)
print(x)  # 타입이 long이므로 소수점이 없이 정수형태로 초기화되었다

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [8]:
# 사용자가 입력한 값으로 텐서 초기화
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [9]:
# 2*4크기, double타입, 1로 채워진 텐서
x = x.new_ones(2,4, dtype=torch.double)
print(x)
print()
y= torch.ones(2,4, dtype=torch.double)
print(x)
print()
print(x == y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

tensor([[True, True, True, True],
        [True, True, True, True]])


In [10]:
# x와 같은 크기, float타입, 무작위로 채워진 텐서
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.1038,  0.5927,  1.9454,  1.7532],
        [ 0.3443,  0.4453, -0.0746,  0.2854]])


In [11]:
# 텐서의 크기 계산
print(x.size())

torch.Size([2, 4])


In [12]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [13]:
# 데이터 타입을 변경 : casting
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [14]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [15]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


## CUDA Tensors

- Pytorch가 gpu를 활용할 수 있는 구조이기 때문에 대표적인 NVIDIA의 CUDA 라이브러리를 사용해야 한다.
- CUDA에서 사용하는 텐서 형태로 cpu나 gpu에 맞게 .to 메서드를 사용하여 텐서를 어떠한 장치(cpu, gpu)로도 옮길 수 있다.

In [18]:
x = torch.randn(1)  # 실제 값으로 랜덤하게 한개 뽑아달라는 명령문
print(x)
print(x.item())     # 실제 값은 int32로 굉장히 길다.
print(x.dtype)

tensor([-1.4753])
-1.4752633571624756
torch.float32


In [20]:
# 먼저 device를 정해야 한다. gpu runtime에 연결되어 있어서 cuda가 가능하면 cuda를 이용하고 아니면 cpu를 이용한다.
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

y = torch.ones_like(x, device=device)
print(y)

x = x.to(device)      # x의 값을 cuda 즉 gpu로 옮겨줘!
print(x)

z = x + y             # x, y 둘 다 gpu에 있는 값들이므로 z역시 cuda에 있다.
print(z)
print(z.to('cpu', dtype=torch.double))   # z값을 cpu로 옮기고 타입은 double로 해줘!

cuda
tensor([1.], device='cuda:0')
tensor([-1.4753], device='cuda:0')
tensor([-0.4753], device='cuda:0')
tensor([-0.4753], dtype=torch.float64)


## 다차원 텐서 표현 : 22:39